---

plugins:
  - jest


env:
  node: true
  es6: true
  jest/globals: true


extends: 
  - 'airbnb-base'
  - "plugin:jest/style"

  
parserOptions: 
  ecmaVersion: 2020
  sourceType: "module"
  

rules:
  no-console: 0
  import/extensions: 0
  
  


